### ISSUE TITLE
Functions undefined when importing from commonjs

### ISSUE THREAD

**Issue by jobackman** [tobiipro/lodash-firecloud#18]
Doing imports from commonjs seems to import undefined:
```js
let _ = require('lodash-firecloud');
```

Was throwing errors like:
```bash
[14:32:55] E/configParser - TypeError: _.defaultsDeep is not a function
    at Object.<anonymous> (/Users/jban/git/tobii/drive/e2e/conf-local.js:36:20)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at ConfigParser.addFileConfig (/Users/jban/git/tobii/drive/node_modules/protractor/built/configParser.js:135:26)
    at Object.initFn [as init] (/Users/jban/git/tobii/drive/node_modules/protractor/built/launcher.js:93:22)
```

Adding `.default` to the import looks to fix it: 
```js
let _ = require('lodash-firecloud').default;
```

Intended or not? 

The commit in question: https://github.com/tobiipro/drive/commit/37b7a112bfee9154be69621ff565e2e8cd4ef38c#diff-8ec2d066d74463a18a844d487e7537a6

**Comment by IanSavchenko** [comment]
I think it would be nice to fix. Is it a problem only with `lodash-firecloud` and not with `lodash`?

**Comment by andreineculau** [comment]
`lodash` is not an esm module, so no.

changing the root `index.js` to the following would fix the issue (backward compat optional)
```js
let _ = require('./lib/index');
// FIXME backward compat. remove on next breaking version
_.default.default = _.default;

module.exports = _;
```

but I didn't digest fully where I stand on this issue. The problem is not just related to `lodash-firecloud` but to any package that presents itself as an esm module, and it required (not esm imported) from node.

so in other words: do we want to keep it as is, or do we want our root `index.js` in all our packages to be go from `module.exports = require('./lib/index');` to `module.exports = require('./lib/index').default;`

PS: the `/index` is redundant. Will clean up sometime all repos...

**Comment by IanSavchenko** [comment]
What I would want is to have a matching behavior. For `lodash` doing `let _ = require('lodash');` gives you a working instance, for `lodash-firecloud` - no. Why should it be different? it does not have to happen for all the packages, but in this case it would be fair.
